name: Deploy Recipe App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run:  yarn 

      - name: Build
        run: npm run build --if-present

      - name: Deploy
        run: |
          echo "Deploying the recipe-app!"

          # Replace the following lines with your actual deployment commands
          git config --global user.email "csahin17072010@gmail.com"
          git config --global user.name "ceyhunsahin"
          git checkout -B gh-pages
          git add -f build/
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages